In [1]:
import pandas as pd

In [5]:
df = pd.read_csv(
    "../data/airbnb-listings.csv",
    sep=";"
)

df.shape

C:\Users\lucia\AppData\Local\Temp\ipykernel_16872\2036566971.py:1: DtypeWarning: Columns (0: ID, 1: Scrape ID, 2: Host Acceptance Rate, 3: Has Availability) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

(494954, 89)

In [6]:
df.columns.tolist()

['ID',
 'Listing Url',
 'Scrape ID',
 'Last Scraped',
 'Name',
 'Summary',
 'Space',
 'Description',
 'Experiences Offered',
 'Neighborhood Overview',
 'Notes',
 'Transit',
 'Access',
 'Interaction',
 'House Rules',
 'Thumbnail Url',
 'Medium Url',
 'Picture Url',
 'XL Picture Url',
 'Host ID',
 'Host URL',
 'Host Name',
 'Host Since',
 'Host Location',
 'Host About',
 'Host Response Time',
 'Host Response Rate',
 'Host Acceptance Rate',
 'Host Thumbnail Url',
 'Host Picture Url',
 'Host Neighbourhood',
 'Host Listings Count',
 'Host Total Listings Count',
 'Host Verifications',
 'Street',
 'Neighbourhood',
 'Neighbourhood Cleansed',
 'Neighbourhood Group Cleansed',
 'City',
 'State',
 'Zipcode',
 'Market',
 'Smart Location',
 'Country Code',
 'Country',
 'Latitude',
 'Longitude',
 'Property Type',
 'Room Type',
 'Accommodates',
 'Bathrooms',
 'Bedrooms',
 'Beds',
 'Bed Type',
 'Amenities',
 'Square Feet',
 'Price',
 'Weekly Price',
 'Monthly Price',
 'Security Deposit',
 'Cleaning Fee',
 'Guests Included',
 'Extra People',
 'Minimum Nights',
 'Maximum Nights',
 'Calendar Updated',
 'Has Availability',
 'Availability 30',
 'Availability 60',
 'Availability 90',
 'Availability 365',
 'Calendar last Scraped',
 'Number of Reviews',
 'First Review',
 'Last Review',
 'Review Scores Rating',
 'Review Scores Accuracy',
 'Review Scores Cleanliness',
 'Review Scores Checkin',
 'Review Scores Communication',
 'Review Scores Location',
 'Review Scores Value',
 'License',
 'Jurisdiction Names',
 'Cancellation Policy',
 'Calculated host listings count',
 'Reviews per Month',
 'Geolocation',
 'Features']

In [7]:
[col for col in df.columns if any(
    word in col.lower()
    for word in ["city", "location", "neighbour", "country", "latitude", "longitude"]
)]

['Host Location',
 'Host Neighbourhood',
 'Neighbourhood',
 'Neighbourhood Cleansed',
 'Neighbourhood Group Cleansed',
 'City',
 'Smart Location',
 'Country Code',
 'Country',
 'Latitude',
 'Longitude',
 'Review Scores Location',
 'Geolocation']

In [8]:
df["City"].head(10)

0    Amsterdam
1    Amsterdam
2    Amsterdam
3    Amsterdam
4    Amsterdam
5    Amsterdam
6    Amsterdam
7    Amsterdam
8    Amsterdam
9    Amsterdam
Name: City, dtype: str

In [9]:
df.loc[
    df["City"].astype(str).str.contains("marseille", case=False, na=False),
    "City"
].value_counts()

Series([], Name: count, dtype: int64)

In [10]:
df["Country"].value_counts().head(20)

Country
United States     134545
United Kingdom     61041
France             56562
Spain              45844
Australia          40693
Italy              33146
Canada             30787
Germany            20576
Denmark            20545
Netherlands        15181
Austria             7893
Belgium             7419
Ireland             6729
Hong Kong           6423
Greece              5127
Switzerland         2381
China                 51
Vatican City           2
Mexico                 2
0                      1
Name: count, dtype: int64

In [11]:
france = df[df["Country"] == "France"]

france.shape

(56562, 89)

In [13]:
france["Smart Location"].value_counts().head(30)

Smart Location
Paris, France                       54491
Paris-19E-Arrondissement, France      170
Paris-15E-Arrondissement, France      148
Paris-18E-Arrondissement, France      121
Paris-20E-Arrondissement, France      112
Paris-16E-Arrondissement, France       94
Paris-11E-Arrondissement, France       90
Paris-10E-Arrondissement, France       81
Paris-17E-Arrondissement, France       77
Paris-13E-Arrondissement, France       76
Paris-14E-Arrondissement, France       75
Paris-12E-Arrondissement, France       70
Paris-4E-Arrondissement, France        64
Paris-3E-Arrondissement, France        61
Boulogne-Billancourt, France           61
Paris-1ER-Arrondissement, France       43
Paris-2E-Arrondissement, France        41
Neuilly-sur-Seine, France              41
Paris-5E-Arrondissement, France        40
Paris-8E-Arrondissement, France        30
PARIS, France                          30
Issy-les-Moulineaux, France            29
Île-de-France, France                  27
Paris-6E-Arrondissement, France        26
paris, France                          24
Paris , France                         21
Saint-Ouen, France                     21
Vincennes, France                      21
Levallois-Perret, France               20
Paris-7E-Arrondissement, France        20
Name: count, dtype: int64

In [14]:
marseille = pd.read_csv(
    "../data/Airbnb_Marseille_France_AirbnbMasterTable_07052026.csv"
)

marseille.shape

(6002, 68)

In [15]:
marseille.head()

,Country,Location,Airbnb_ListingID,Scrape_Date,Lat,Lng,MapMarkerType,City,ListingTitle,Bathrooms,...,OutlierPrice_PerBedroom,OutlierPrice_PerGuest,AvailableOverThanTwoWeeks,AvailableOver30Days,AvailableOver90Days,AvailableOver180Days,AvailableMoreThan30Days,AvailableMoreThan90Days,AvailableMoreThan180Days,RecordInserted
0,France,Marseille,1.092830e+18,2026-05-06 20:52:24,43.298900,5.387800,EXACT,Marseille,Chic and quiet in the heart of the city,1.0,...,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,2026-05-06 20:52:24.000000
1,France,Marseille,1.094990e+18,2026-05-06 12:21:49,43.236674,5.403806,APPROX,Marseille,Renovated house with pool,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2026-05-06 12:21:49.000000
2,France,Marseille,1.099327e+18,2026-05-07 04:56:34,43.300200,5.368700,EXACT,Marseille,Charming T2 in the heart of Le Panier,1.0,...,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,2026-05-07 04:56:34.000000
3,France,Marseille,1.132605e+18,2026-05-06 10:36:23,43.294290,5.437980,APPROX,Marseille,rooms wanted Marseille,NaN,...,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2026-05-06 10:36:23.000000
4,France,Marseille,1.133975e+18,2026-05-06 18:36:10,43.282000,5.373740,APPROX,Marseille,House and garden in the heart of Marseille.,1.0,...,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,2026-05-06 18:36:10.000000

In [16]:
marseille.columns.tolist()

['Country',
 'Location',
 'Airbnb_ListingID',
 'Scrape_Date',
 'Lat',
 'Lng',
 'MapMarkerType',
 'City',
 'ListingTitle',
 'Bathrooms',
 'Bedrooms',
 'Beds',
 'PersonCapacity',
 'is_NewListing',
 'PictureCount',
 'is_GuestFavourite',
 'Host_ID',
 'Host_FirstName',
 'Host_isSuperhost',
 'Host_MultipleListings',
 'Host_MultipleListingsGlobal',
 'RoomType',
 'RoomType_Clean',
 'SpaceType',
 'SpaceType_Clean',
 'RoomAndPropertyType',
 'IsHomeOrServicedApartment',
 'ReviewCount',
 'StarRating',
 'RatingPct_5star',
 'RatingPct_4star',
 'RatingPct_3star',
 'RatingPct_2star',
 'RatingPct_1star',
 'LocationRating',
 'CleanlinessRating',
 'ValueRating',
 'AccuracyRating',
 'CheckinRating',
 'CommunicationRating',
 'VisibleReviewCount',
 'IsLowReviewScore',
 'NoReviewsNotNew',
 'Road',
 'Neighbourhood',
 'Suburb',
 'AddressCity',
 'StateDistrict',
 'Postcode',
 'IndexInSearchEngines',
 'BasicNightPrice_CheckIn',
 'BasicNightPrice_CheckOut',
 'Currency',
 'PrimaryPriceString',
 'BasicNightPrice',
 'BasicNightPrice_USD',
 'Taxes',
 'Taxes_USD',
 'OutlierPrice_PerBedroom',
 'OutlierPrice_PerGuest',
 'AvailableOverThanTwoWeeks',
 'AvailableOver30Days',
 'AvailableOver90Days',
 'AvailableOver180Days',
 'AvailableMoreThan30Days',
 'AvailableMoreThan90Days',
 'AvailableMoreThan180Days',
 'RecordInserted']

In [17]:
for col in marseille.columns:
    print(col)

Country
Location
Airbnb_ListingID
Scrape_Date
Lat
Lng
MapMarkerType
City
ListingTitle
Bathrooms
Bedrooms
Beds
PersonCapacity
is_NewListing
PictureCount
is_GuestFavourite
Host_ID
Host_FirstName
Host_isSuperhost
Host_MultipleListings
Host_MultipleListingsGlobal
RoomType
RoomType_Clean
SpaceType
SpaceType_Clean
RoomAndPropertyType
IsHomeOrServicedApartment
ReviewCount
StarRating
RatingPct_5star
RatingPct_4star
RatingPct_3star
RatingPct_2star
RatingPct_1star
LocationRating
CleanlinessRating
ValueRating
AccuracyRating
CheckinRating
CommunicationRating
VisibleReviewCount
IsLowReviewScore
NoReviewsNotNew
Road
Neighbourhood
Suburb
AddressCity
StateDistrict
Postcode
IndexInSearchEngines
BasicNightPrice_CheckIn
BasicNightPrice_CheckOut
Currency
PrimaryPriceString
BasicNightPrice
BasicNightPrice_USD
Taxes
Taxes_USD
OutlierPrice_PerBedroom
OutlierPrice_PerGuest
AvailableOverThanTwoWeeks
AvailableOver30Days
AvailableOver90Days
AvailableOver180Days
AvailableMoreThan30Days
AvailableMoreThan90Days
AvailableMoreThan180Days
RecordInserted

In [18]:
[col for col in marseille.columns if "price" in col.lower()]

['BasicNightPrice_CheckIn',
 'BasicNightPrice_CheckOut',
 'PrimaryPriceString',
 'BasicNightPrice',
 'BasicNightPrice_USD',
 'OutlierPrice_PerBedroom',
 'OutlierPrice_PerGuest']

In [19]:
marseille[
    [
        "BasicNightPrice_CheckIn",
        "BasicNightPrice_CheckOut",
        "PrimaryPriceString",
        "BasicNightPrice",
        "BasicNightPrice_USD",
        "OutlierPrice_PerBedroom",
        "OutlierPrice_PerGuest"
    ]
].head(10)

,BasicNightPrice_CheckIn,BasicNightPrice_CheckOut,PrimaryPriceString,BasicNightPrice,BasicNightPrice_USD,OutlierPrice_PerBedroom,OutlierPrice_PerGuest
0,2026-07-03,2026-07-08,5 nights x € 120.77,120.0,140.77,0.0,0.0
1,2026-07-23,2026-07-30,7 nights x € 195.46,195.0,228.75,0.0,0.0
2,2026-06-23,2026-06-28,5 nights x € 110.39,110.0,129.04,0.0,0.0
3,2026-05-07,2026-05-12,5 nights x € 93.55,93.0,109.10,0.0,0.0
4,2026-05-31,2026-06-05,5 nights x € 171.44,171.0,200.60,0.0,0.0
5,2026-09-01,2026-09-06,5 nights x € 53.79,53.0,62.17,0.0,0.0
6,2026-05-08,2026-05-15,7 nights x € 720.02,720.0,844.63,0.0,0.0
7,2026-08-18,2026-08-23,5 nights x € 145.01,145.0,170.10,0.0,0.0
8,2027-01-18,2027-01-23,5 nights x € 94.96,94.0,110.27,0.0,0.0
9,2026-05-24,2026-05-29,5 nights x € 123.00,123.0,144.29,0.0,0.0

In [20]:
marseille["BasicNightPrice"].describe()

count     5995.00000
mean       179.27990
std        276.84786
min         25.00000
25%         93.00000
50%        124.00000
75%        187.00000
max      11752.00000
Name: BasicNightPrice, dtype: float64

In [21]:
marseille.nlargest(
    10,
    "BasicNightPrice"
)[["BasicNightPrice", "PrimaryPriceString"]]

      BasicNightPrice      PrimaryPriceString
5503          11752.0  5 nights x € 11,752.59
4381          10524.0  5 nights x € 10,524.71
2601           4480.0   5 nights x € 4,480.95
5930           3536.0   5 nights x € 3,536.30
1824           3524.0   5 nights x € 3,524.61
2232           3518.0   5 nights x € 3,518.76
425            2748.0   5 nights x € 2,748.12
3348           2650.0   5 nights x € 2,650.00
5492           2500.0   5 nights x € 2,500.00
4116           2287.0   7 nights x € 2,287.77

In [22]:
marseille.nlargest(
    10,
    "BasicNightPrice"
)[
    [
        "BasicNightPrice_CheckIn",
        "BasicNightPrice_CheckOut",
        "PrimaryPriceString",
        "BasicNightPrice"
    ]
]

,BasicNightPrice_CheckIn,BasicNightPrice_CheckOut,PrimaryPriceString,BasicNightPrice
5503,2026-05-07,2026-05-12,"5 nights x € 11,752.59",11752.0
4381,2026-05-06,2026-05-11,"5 nights x € 10,524.71",10524.0
2601,2026-06-04,2026-06-09,"5 nights x € 4,480.95",4480.0
5930,2026-11-17,2026-11-22,"5 nights x € 3,536.30",3536.0
1824,2026-08-29,2026-09-03,"5 nights x € 3,524.61",3524.0
2232,2026-09-12,2026-09-17,"5 nights x € 3,518.76",3518.0
425,2026-05-26,2026-05-31,"5 nights x € 2,748.12",2748.0
3348,2026-05-06,2026-05-11,"5 nights x € 2,650.00",2650.0
5492,2026-05-07,2026-05-12,"5 nights x € 2,500.00",2500.0
4116,2026-05-14,2026-05-21,"7 nights x € 2,287.77",2287.0

In [23]:
marseille.loc[5503]

Country                                         France
Location                                     Marseille
Airbnb_ListingID                 1091225851621574912.0
Scrape_Date                        2026-05-06 11:30:17
Lat                                          43.307004
                                       ...
AvailableOver180Days                               0.0
AvailableMoreThan30Days                            1.0
AvailableMoreThan90Days                            0.0
AvailableMoreThan180Days                           0.0
RecordInserted              2026-05-06 11:30:17.000000
Name: 5503, Length: 68, dtype: object

In [24]:
[col for col in marseille.columns if any(
    word in col.lower()
    for word in ["name", "bed", "bath", "guest", "room", "property", "location"]
)]

['Location',
 'Bathrooms',
 'Bedrooms',
 'Beds',
 'is_GuestFavourite',
 'Host_FirstName',
 'RoomType',
 'RoomType_Clean',
 'RoomAndPropertyType',
 'LocationRating',
 'OutlierPrice_PerBedroom',
 'OutlierPrice_PerGuest']

In [25]:
marseille.loc[
    5503,
    [
        "BasicNightPrice",
        "Location",
        "Bathrooms",
        "Bedrooms",
        "Beds",
        "RoomType",
        "RoomType_Clean",
        "RoomAndPropertyType",
        "LocationRating",
        "OutlierPrice_PerBedroom",
        "OutlierPrice_PerGuest"
    ]
]

BasicNightPrice                     11752.0
Location                          Marseille
Bathrooms                               5.0
Bedrooms                                6.0
Beds                                    6.0
RoomType                   Entire home/flat
RoomType_Clean                  Entire Home
RoomAndPropertyType            Entire villa
LocationRating                          NaN
OutlierPrice_PerBedroom                 1.0
OutlierPrice_PerGuest                   1.0
Name: 5503, dtype: object

In [26]:
[col for col in marseille.columns if any(
    word in col.lower()
    for word in ["accommod", "capacity", "person", "people"]
)]

['PersonCapacity']

In [27]:
villas = marseille[
    marseille["RoomAndPropertyType"].str.contains(
        "villa", case=False, na=False
    )
]

villas.shape

(212, 68)

In [28]:
villas["BasicNightPrice"].describe()

count      212.000000
mean       518.311321
std        909.688534
min         35.000000
25%        219.000000
50%        382.000000
75%        564.000000
max      11752.000000
Name: BasicNightPrice, dtype: float64

In [29]:
villas.nlargest(
    10,
    "BasicNightPrice"
)[
    [
        "BasicNightPrice",
        "Bedrooms",
        "Bathrooms",
        "Beds",
        "OutlierPrice_PerBedroom",
        "OutlierPrice_PerGuest"
    ]
]

,BasicNightPrice,Bedrooms,Bathrooms,Beds,OutlierPrice_PerBedroom,OutlierPrice_PerGuest
5503,11752.0,6.0,5.0,6.0,1.0,1.0
2601,4480.0,2.0,3.0,2.0,1.0,1.0
425,2748.0,5.0,5.0,5.0,1.0,1.0
3348,2650.0,4.0,4.0,4.0,1.0,1.0
5492,2500.0,4.0,4.0,4.0,1.0,1.0
3539,1732.0,6.0,5.0,6.0,0.0,0.0
4695,1487.0,9.0,6.0,9.0,0.0,0.0
1545,1363.0,4.0,4.0,4.0,1.0,1.0
5940,1132.0,5.0,5.5,5.0,0.0,0.0
5704,1123.0,5.0,5.0,5.0,0.0,0.0

In [30]:
villas_outliers = villas[
    villas["BasicNightPrice"] > 1081.5
]

villas_outliers.shape

(13, 68)

In [31]:
villas_outliers[
    [
        "BasicNightPrice",
        "Bedrooms",
        "Bathrooms",
        "Beds"
    ]
].sort_values("BasicNightPrice")

      BasicNightPrice  Bedrooms  Bathrooms  Beds
2178           1085.0       4.0        3.0   4.0
357            1086.0       6.0        5.5   6.0
1826           1099.0       5.0        3.0   5.0
5704           1123.0       5.0        5.0   5.0
5940           1132.0       5.0        5.5   5.0
1545           1363.0       4.0        4.0   4.0
4695           1487.0       9.0        6.0   9.0
3539           1732.0       6.0        5.0   6.0
5492           2500.0       4.0        4.0   4.0
3348           2650.0       4.0        4.0   4.0
425            2748.0       5.0        5.0   5.0
2601           4480.0       2.0        3.0   2.0
5503          11752.0       6.0        5.0   6.0

In [32]:
marseille.info()

<class 'pandas.DataFrame'>
RangeIndex: 6002 entries, 0 to 6001
Data columns (total 68 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Country                      6001 non-null   str
 1   Location                     6000 non-null   str
 2   Airbnb_ListingID             6000 non-null   float64
 3   Scrape_Date                  6000 non-null   str
 4   Lat                          6000 non-null   float64
 5   Lng                          6000 non-null   float64
 6   MapMarkerType                6000 non-null   str
 7   City                         6000 non-null   str
 8   ListingTitle                 6000 non-null   str
 9   Bathrooms                    5902 non-null   float64
 10  Bedrooms                     5511 non-null   float64
 11  Beds                         5989 non-null   float64
 12  PersonCapacity               6000 non-null   float64
 13  is_NewListing                6000 non-null   object
 14  PictureCount                 6000 non-null   float64
 15  is_GuestFavourite            6000 non-null   object
 16  Host_ID                      6000 non-null   float64
 17  Host_FirstName               5997 non-null   str
 18  Host_isSuperhost             6000 non-null   object
 19  Host_MultipleListings        6000 non-null   float64
 20  Host_MultipleListingsGlobal  6000 non-null   float64
 21  RoomType                     6000 non-null   str
 22  RoomType_Clean               6000 non-null   str
 23  SpaceType                    6000 non-null   str
 24  SpaceType_Clean              6000 non-null   str
 25  RoomAndPropertyType          6000 non-null   str
 26  IsHomeOrServicedApartment    6000 non-null   float64
 27  ReviewCount                  6000 non-null   float64
 28  StarRating                   5350 non-null   float64
 29  RatingPct_5star              4869 non-null   float64
 30  RatingPct_4star              4869 non-null   float64
 31  RatingPct_3star              4869 non-null   float64
 32  RatingPct_2star              4869 non-null   float64
 33  RatingPct_1star              4869 non-null   float64
 34  LocationRating               5350 non-null   float64
 35  CleanlinessRating            5350 non-null   float64
 36  ValueRating                  5350 non-null   float64
 37  AccuracyRating               5350 non-null   float64
 38  CheckinRating                5350 non-null   float64
 39  CommunicationRating          5350 non-null   float64
 40  VisibleReviewCount           6000 non-null   float64
 41  IsLowReviewScore             6000 non-null   float64
 42  NoReviewsNotNew              6000 non-null   float64
 43  Road                         5858 non-null   str
 44  Neighbourhood                547 non-null    str
 45  Suburb                       6000 non-null   str
 46  AddressCity                  5814 non-null   str
 47  StateDistrict                6000 non-null   str
 48  Postcode                     6000 non-null   float64
 49  IndexInSearchEngines         6000 non-null   object
 50  BasicNightPrice_CheckIn      6000 non-null   str
 51  BasicNightPrice_CheckOut     6000 non-null   str
 52  Currency                     6000 non-null   str
 53  PrimaryPriceString           5995 non-null   str
 54  BasicNightPrice              5995 non-null   float64
 55  BasicNightPrice_USD          5995 non-null   float64
 56  Taxes                        5994 non-null   float64
 57  Taxes_USD                    5994 non-null   float64
 58  OutlierPrice_PerBedroom      6000 non-null   float64
 59  OutlierPrice_PerGuest        6000 non-null   float64
 60  AvailableOverThanTwoWeeks    6000 non-null   float64
 61  AvailableOver30Days          6000 non-null   float64
 62  AvailableOver90Days          6000 non-null   float64
 63  AvailableOver180Days         6000 non-null   float64
 64  AvailableMoreThan30Days      6000 non-null   float64
 65  AvailableMoreThan90Days      6000 non-null   float64
 66  AvailableMoreThan180Days     6000 non-null   float64
 67  RecordInserted               6000 non-null   str
dtypes: float64(42), object(4), str(22)
memory usage: 5.0+ MB

In [33]:
missing = marseille.isnull().sum().sort_values(ascending=False)

missing.head(15)

Neighbourhood          5455
RatingPct_4star        1133
RatingPct_1star        1133
RatingPct_3star        1133
RatingPct_2star        1133
RatingPct_5star        1133
ValueRating             652
CommunicationRating     652
AccuracyRating          652
CheckinRating           652
CleanlinessRating       652
LocationRating          652
StarRating              652
Bedrooms                491
AddressCity             188
dtype: int64

In [34]:
missing_pct = (
    marseille.isnull().mean() * 100
).sort_values(ascending=False)

missing_pct.head(15)

Neighbourhood          90.886371
RatingPct_4star        18.877041
RatingPct_1star        18.877041
RatingPct_3star        18.877041
RatingPct_2star        18.877041
RatingPct_5star        18.877041
ValueRating            10.863046
CommunicationRating    10.863046
AccuracyRating         10.863046
CheckinRating          10.863046
CleanlinessRating      10.863046
LocationRating         10.863046
StarRating             10.863046
Bedrooms                8.180606
AddressCity             3.132289
dtype: float64

In [35]:
[col for col in marseille.columns if any(
    word in col.lower()
    for word in ["lat", "lon", "geo", "postal", "zipcode", "district"]
)]

['Lat', 'StateDistrict']

In [36]:
marseille["StateDistrict"].value_counts(dropna=False).head(30)

StateDistrict
Provence-Alpes-Côte d'Azur    6000
NaN                              2
Name: count, dtype: int64

In [37]:
[col for col in marseille.columns if any(
    word in col.lower()
    for word in ["lat", "lng", "lon", "long", "coord", "geo"]
)]

['Lat', 'Lng']

In [38]:
marseille[["Lat", "Lng"]].describe()

               Lat          Lng
count  6000.000000  6000.000000
mean     43.290121     5.387938
std       0.028066     0.030036
min      43.207200     5.326940
25%      43.280600     5.369700
50%      43.292435     5.381535
75%      43.301100     5.397400
max      43.393400     5.522470

In [39]:
marseille[["Lat", "Lng"]].isna().sum()

Lat    2
Lng    2
dtype: int64

In [40]:
for col in marseille.columns:
    print(col)

Country
Location
Airbnb_ListingID
Scrape_Date
Lat
Lng
MapMarkerType
City
ListingTitle
Bathrooms
Bedrooms
Beds
PersonCapacity
is_NewListing
PictureCount
is_GuestFavourite
Host_ID
Host_FirstName
Host_isSuperhost
Host_MultipleListings
Host_MultipleListingsGlobal
RoomType
RoomType_Clean
SpaceType
SpaceType_Clean
RoomAndPropertyType
IsHomeOrServicedApartment
ReviewCount
StarRating
RatingPct_5star
RatingPct_4star
RatingPct_3star
RatingPct_2star
RatingPct_1star
LocationRating
CleanlinessRating
ValueRating
AccuracyRating
CheckinRating
CommunicationRating
VisibleReviewCount
IsLowReviewScore
NoReviewsNotNew
Road
Neighbourhood
Suburb
AddressCity
StateDistrict
Postcode
IndexInSearchEngines
BasicNightPrice_CheckIn
BasicNightPrice_CheckOut
Currency
PrimaryPriceString
BasicNightPrice
BasicNightPrice_USD
Taxes
Taxes_USD
OutlierPrice_PerBedroom
OutlierPrice_PerGuest
AvailableOverThanTwoWeeks
AvailableOver30Days
AvailableOver90Days
AvailableOver180Days
AvailableMoreThan30Days
AvailableMoreThan90Days
AvailableMoreThan180Days
RecordInserted

In [41]:
features = [
    "Bedrooms",
    "Bathrooms",
    "Beds",
    "RoomType",
    "Lat",
    "Lng",
    "PersonCapacity",
    "Postcode",
    "AddressCity",
    "ValueRating",
    "IsHomeOrServicedApartment"
]

marseille[features].info()

<class 'pandas.DataFrame'>
RangeIndex: 6002 entries, 0 to 6001
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Bedrooms                   5511 non-null   float64
 1   Bathrooms                  5902 non-null   float64
 2   Beds                       5989 non-null   float64
 3   RoomType                   6000 non-null   str
 4   Lat                        6000 non-null   float64
 5   Lng                        6000 non-null   float64
 6   PersonCapacity             6000 non-null   float64
 7   Postcode                   6000 non-null   float64
 8   AddressCity                5814 non-null   str
 9   ValueRating                5350 non-null   float64
 10  IsHomeOrServicedApartment  6000 non-null   float64
dtypes: float64(9), str(2)
memory usage: 658.8 KB

In [42]:
marseille[features].isna().mean().sort_values(ascending=False) * 100

ValueRating                  10.863046
Bedrooms                      8.180606
AddressCity                   3.132289
Bathrooms                     1.666111
Beds                          0.216594
RoomType                      0.033322
Lat                           0.033322
PersonCapacity                0.033322
Lng                           0.033322
Postcode                      0.033322
IsHomeOrServicedApartment     0.033322
dtype: float64

In [43]:
marseille["AddressCity"].value_counts(dropna=False).head(20)

AddressCity
Marseille    5814
NaN           188
Name: count, dtype: int64

In [44]:
marseille["Postcode"].value_counts(dropna=False).head(30)

Postcode
13008.0    878
13001.0    849
13007.0    808
13006.0    570
13002.0    518
13009.0    432
13005.0    384
13004.0    290
13003.0    195
13012.0    193
13010.0    169
13013.0    164
13011.0    118
13015.0     92
13190.0     89
13014.0     83
13016.0     49
13380.0     32
13170.0     30
13302.0     19
13821.0     15
13260.0     10
13240.0      9
13400.0      2
NaN          2
13331.0      1
10003.0      1
Name: count, dtype: int64

In [45]:
marseille_postcodes = [
    13001, 13002, 13003, 13004,
    13005, 13006, 13007, 13008,
    13009, 13010, 13011, 13012,
    13013, 13014, 13015, 13016
]

marseille["is_marseille_postcode"] = (
    marseille["Postcode"].isin(marseille_postcodes)
)

In [46]:
marseille["is_marseille_postcode"].value_counts()

is_marseille_postcode
True     5792
False     210
Name: count, dtype: int64

In [47]:
df_clean = marseille[
    marseille["is_marseille_postcode"]
].copy()

df_clean.shape

(5792, 69)